FROM ubuntu@sha256:fa17826afb526a9fc7250e0fbcbfd18d03fe7a54849472f86879d8bf562c629e AS build-env

ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /usr/src

RUN apt-get update && apt-get install -y \
      git \
      curl \
      locales \
      build-essential=12.8ubuntu1.1 \
      python3-pip=20.0.2-5ubuntu1.11 \
      && apt-get clean
RUN pip install cmake==3.31.1

ARG LOCALE=en_US.UTF-8
RUN locale-gen ${LOCALE} && \
    update-locale LANG=${LOCALE}
ENV TZ=Etc/UTC \
    LANG=${LOCALE} \
    LANGUAGE=${LOCALE} \
    LC_ALL=${LOCALE} \
    LC_CTYPE=${LOCALE}

FROM build-env AS onnxruntime-srcs
# Clone the onnxruntime repository at the release v1.20.0 tag.
RUN git clone --branch v1.20.0 https://github.com/microsoft/onnxruntime.git

WORKDIR /usr/src/onnxruntime
# requirements.txt is version-pinned.
RUN pip install -r requirements.txt

FROM onnxruntime-srcs AS build-stage
RUN ./build.sh --config Release \
     --build_shared_lib \
     --parallel \
     --skip_submodule_sync \
     --update \
     --build \
     --allow_running_as_root \
     && cp build/Linux/Release/libonnxruntime.so.1.20.0 /tmp/

RUN echo "69fd3650dd81fa2816016578714f3dd35dce94e2acf43e6d64ad1752a30ab7f3  /tmp/libonnxruntime.so.1.20.0" > /tmp/expected_hash.txt && \
    sha256sum -c /tmp/expected_hash.txt

FROM scratch AS build-binary
COPY --from=build-stage /tmp/libonnxruntime.so.1.20.0 /libonnxruntime.so.1.20.0
